# Generated by Django 4.1.2 on 2022-10-06 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("city", models.CharField(max_length=50)),
                (
                    "area_of_expertise",
                    models.CharField(
                        choices=[
                            ("Allergy and Immunology", "Allergy And Immunology"),
                            ("Anesthesiology", "Anesthesiology"),
                            ("Colon and Rectal Surgery", "Colon And Rectal Surgery"),
                            ("Dermatology", "Dermatology"),
                            ("Emergency Medicine", "Emergency Medicine"),
                        ],
                        max_length=254,
                    ),
                ),
                ("facility", models.CharField(max_length=254)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
